options:
  max-time: 10
pipelines:
  default:
    - step: &build_step
        name: Build
        image:
          name: myprocessx/dotnet-build
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
        caches:
          - dotnetcore
        script:
          - git submodule update --init
          - dotnet nuget add source -n ozma -u "$NUGET_USER" -p "$NUGET_PASSWORD" --store-password-in-clear-text "$NUGET_URL"
          - ./build.sh
        artifacts:
          - FunDB/bin/*/*/publish/**
  pull-requests:
    '**':
      - step: *build_step
  branches:
    master:
      - step:
          name: Build and upload
          image:
            name: myprocessx/dotnet-build
            username: $DOCKER_HUB_USER
            password: $DOCKER_HUB_PASSWORD
          caches:
            - dotnetcore
            - docker
          script:
            - git submodule update --init
            - dotnet nuget add source -n ozma -u "$NUGET_USER" -p "$NUGET_PASSWORD" --store-password-in-clear-text "$NUGET_URL"
            - ./build.sh
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            # Workaround for pipes not supporting private docker repos.
            - docker pull myprocessx/upload-artifact
            - pipe: ozma-io/upload-artifact:master
              variables:
                LOCAL_PATH: FunDB/bin/*/*/publish
          artifacts:
            - artifact.json
      - step:
          name: Deploy to test
          deployment: test
          caches:
            - docker
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - docker pull myprocessx/deploy-artifact
            - pipe: ozma-io/deploy-artifact:master
          artifacts:
            - artifact.json
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          caches:
            - docker
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - docker pull myprocessx/deploy-artifact
            - pipe: ozma-io/deploy-artifact:master
