FROM mcr.microsoft.com/dotnet/core/sdk:3.1

# Install Mono (for FsLexYacc build steps).
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get -y install mono-runtime libmono-system-core4.0-cil \
  && rm -rf /var/lib/apt/lists/*
