name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore NetJs Dependencies
        run: |
          dotnet restore --locked-mode

      - name: Build
        run: |
          dotnet build -c Release --no-restore
      - name: Publish
        run: |
          dotnet publish -o ozmadb -c Release --no-restore -r linux-x64 --self-contained true /p:UseAppHost=true OzmaDB/OzmaDB.fsproj
          tar -c ozmadb | xz > ozmadb.tar.xz
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            ozmadb.tar.xz
