name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore
        run: |
          dotnet restore --locked-mode -r linux-x64
      - name: Publish
        run: |
          dotnet publish -o out/ozmadb -c Release -r linux-x64 OzmaDB/OzmaDB.fsproj
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ozmadb
          path: |
            out/ozmadb
